# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160613_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_Text',
            new_name='question_text',
        ),
    ]
